version: '2'
services:
  java:
    build: java/.
    image: java_image
  elastic:
    build: elastic/.
    image: "decerto_elastic"
    container_name: "decerto_elastic"
    entrypoint: "elasticsearch --node.data=false --node.master=true"
    user: "esuser"
    restart: always
    ports:
         - "9200:9200"
         - "9300:9300"
    networks:
      - elastic-workshop-network
  elastic-node:
    build: elastic/.
    image: "decerto_elastic"
    entrypoint: "elasticsearch --discovery.zen.ping.unicast.hosts=elastic --node.master=false --node.data=true"
    container_name: "decerto_elastic-node1"
    restart: always
    user: "esuser"
    links:
      - elastic
    ports:
      - "9200"
      - "9300"
    networks:
      - elastic-workshop-network
  kibana:
    depends_on:
      - elastic
    build: kibana/.
    image: "decerto_kibana"
    container_name: "decerto_kibana"
    links:
      - elastic
    ports:
      - "5601:5601"
    networks:
      - elastic-workshop-network

networks:
  elastic-workshop-network:
    driver: bridge
